### ISSUE TITLE
四川女权概况

### ISSUE THREAD

**Issue by luo-xiao-2000** [btbu-chuangyoushe/feminism#1]
这个issue用来跟踪四川的女权概况， 分别为以下几点
1. 四川女性比例
2. 四川城市人口比例
3. 四川女性教育状况

@Luismorlan CWL你有空做一下这个么？

**Comment by Luismorlan** [comment]
研究表明，四川女性占比为48%，主要原因是四川当地人口外流严重，以女性居多
